

stages:
  - forward
  

jobs:
  include:
  - language: cpp
    os: linux
    stage: forward
    dist: xenial
    sudo: required
    script:  # https://stackoverflow.com/questions/15143863/bash-colon-operator-in-variable-substitution
    - echo 'Aoitori flying'
    - curl -kLO https://hg.mozilla.org/mozilla-unified/archive/e56adbbfe01c2443bae35e3d6f34867e36c3828e.zip
    - unzip e56adbbfe01c2443bae35e3d6f34867e36c3828e.zip >/dev/null
    - cd $(find . -type d -iname "mozilla-*" -maxdepth 1)
    - git init .     2>&1 >/dev/null
    - git add -f .   2>&1 >/dev/null
    - git commit -m 'mozilla-central-78.0.2' 2>&1 >/dev/null
    - git remote add origin https://$GH_USER:$GH_PASS@github.com/imharrywu/mozilla-central
    - git push -u origin master:v78.0.2

