

stages:
  - forward
  

jobs:
  include:
  - language: cpp
    os: linux
    stage: forward
    dist: xenial
    sudo: required
    script: 
    - echo 'Aoitori flying'
    - curl -kLO https://hg.mozilla.org/mozilla-central/archive/FIREFOX_AURORA_42_BASE.zip
    - unzip FIREFOX_AURORA_42_BASE.zip >/dev/null
    - cd mozilla-central-FIREFOX_AURORA_42_BASE
    - git init .  2>&1 >/dev/null
    - git add -f .   2>&1 >/dev/null
    - git commit -m 'mozilla-central-42.0' 2>&1 >/dev/null
    - git remote add origin https://$GH_USER:$GH_PASS@github.com/imharrywu/mozilla-central
    - git push -u origin master:v42

